//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersoManagerLibrary.ModelLibrary.EntityFrameworkLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public Card()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public long ID { get; set; }
        public string CardPan { get; set; }
        public string HashedCardPan { get; set; }
        public Nullable<long> CardProfileID { get; set; }
        public Nullable<long> RequestingBranch { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> CardExpiryDate { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual CardProfile CardProfile { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
