//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersoManagerLibrary.ModelLibrary.EntityFrameworkLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public long ID { get; set; }
        public string Surname { get; set; }
        public string Othernames { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<long> CustomerCard { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> CustomerBranch { get; set; }
        public Nullable<bool> Downloaded { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual Branch Branch { get; set; }
    }
}
